### ISSUE TITLE
Able to access client dashboard without logging in

### ISSUE THREAD

**Issue by junaed1995** [bisho1995/join-us-design-lab#15]
When opening the platform and clicking on "Client Dashboard", it is accessible even when not logged in.
Step-1
Open the home page http://localhost:3000/ 
Step-2
Click on "Client Dashboard",   http://localhost:3000/client-dashboard   . Client Dashboard opens without being logged in.

**Comment by bisho1995** [comment]
Done

**Comment by arnabnandy1996** [comment]
Its was happened for previously there was no logout button and first login was still present. So, Now logout button available, and 1 client have to login to access the dashboard and he/she can logout.
